services:
  postgres-db:
    image: postgres:latest
    container_name: biblioteca-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ClaveSecreta123
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      # CAMBIO CLAVE: Remaniobramos el punto de montaje a la raíz de la librería de postgres
      - biblioteca_postgres_data:/var/lib/postgresql
  structurizr:
    image: structurizr/structurizr
    container_name: mi-structurizr
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./docs/architecture/structurizr:/usr/local/structurizr
    command: local

volumes:
  biblioteca_postgres_data:

