# Identificador único para tu sistema de biblioteca
sonar.projectKey=sistema-gestion-biblioteca
sonar.projectName=Sistema de Gestion de Biblioteca y Equipos

# Ubicación del código fuente (Analiza la raíz para buscar tu backend/frontend)
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Exclusiones críticas para este proyecto específico
# Evitamos analizar la documentación de arquitectura, diagramas e imágenes para acelerar el proceso
sonar.exclusions=docs/architecture/**, **/node_modules/**, **/dist/**, **/.git/**, **/.gitignore
sonar.exclusions=**/node_modules/**, **/dist/**, sonar.sh


# Configuración dinámica y segura de credenciales
#sonar.host.url=${env.SONAR_HOST_URL}
#sonar.token=${env.SONAR_TOKEN}

